language: java

jdk:
- oraclejdk8

script:
- ./gradlew clean build test
- ./gradlew :helios-docs:runAnk
- ./gradlew :helios-benchmarks:executeHeliosBenchmark
- ./gradlew :helios-benchmarks:compareBenchmarkCI
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_COMMIT_MESSAGE" != "Upload benchmark"]; then
  ./gradlew :helios-benchmarks:executeMasterBenchmark;
  ./gradlew :helios-benchmarks:uploadBenchmark;
  fi