language: java

jdk:
- oraclejdk8

script:
- ./gradlew clean build test
- ./gradlew :helios-docs:runAnk
- ./gradlew :helios-benchmarks:executeHeliosBenchmark
- ./gradlew :helios-benchmarks:executeMasterBenchmark
- ./gradlew :helios-benchmarks:compareBenchmarkCI
- if [ "$TRAVIS_BRANCH" = "master" ]; then
  echo $TRAVIS_BRANCH;
  echo $TRAVIS_PULL_REQUEST;
  fi
