language: java

jdk:
- oraclejdk8

script:
- ./gradlew clean build test
- ./gradlew :helios-docs:runAnk
- if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew :helios-benchmarks:uploadMasterBenchmark; fi
