language: java

jdk:
- oraclejdk8

script:
- ./gradlew clean build test
- ./gradlew :helios-docs:runAnk
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
  ./gradlew :helios-benchmarks:executeMasterBenchmark;
  ./gradlew :helios-benchmarks:uploadBenchmark;
  fi