language: java

jdk:
- oraclejdk8

stages:
  - name: build
  - name: benchmark
  - name: upload
    if: branch = master AND type != pull_request AND sender != 47degdev

jobs:
  include:
    - stage: build
      script:
        - ./gradlew clean build test
        - ./gradlew :helios-docs:runAnk
    - stage: benchmark
      script:
        - ./gradlew :helios-benchmarks:executeHeliosBenchmark
        - ./gradlew :helios-benchmarks:compareBenchmarkCI
    - stage: upload
      script:
        - ./gradlew :helios-benchmarks:executeMasterBenchmark
        - ./gradlew :helios-benchmarks:uploadBenchmark