language: java

jdk:
- oraclejdk8

script:
- ./gradlew clean build test
- ./gradlew :helios-docs:runAnk
- ./gradlew :helios-benchmarks:executeHeliosBenchmark
- ./gradlew :helios-benchmarks:executeMasterBenchmark
- ./gradlew :helios-benchmarks:compareBenchmark
- if [ "$TRAVIS_BRANCH" = "master" ]; then ./gradlew :helios-benchmarks:executeMasterBenchmark; fi
